version: '3.8'

services:
  backend:
    image: jongung/waka-be:1.0
    restart: always
    ports:
      - 18083:18083
    environment:
      SQL_IP: mysql
      SQL_ID: root
      SQL_PASSWORD: mega123
      SQL_PORT: 3306
  
  mysql:
    image: library/mysql:5.7
    restart: always
    volumes:
      - db_datas:/var/lib/mysql
    environment:
      MYSQL_DATABASE: megatime
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: mega123
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 23306:3306

volumes:
  db_datas:
